# Generated by Django 5.2.11 on 2026-02-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
